config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'help#api'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :budokop_sensors, only: [:index, :show, :update, :create]
      resources :device_aggregations, only: [:index, :show, :update, :create]
      resources :devices, only: [:index, :show, :update, :create]
      resources :edge_nodes, only: [:index, :show, :update, :create]
      resources :levees, only: [:index, :show, :update]
      resources :measurement_nodes, only: [:index, :show, :update, :create]
      resources :measurements, only: [:index, :show, :update, :create]
      resources :neosentio_sensors, only: [:index, :show, :update, :create]
      resources :parameters, only: [:index, :show, :update, :create]
      resources :pumps, only: [:index, :show, :update, :create]
      resources :fiber_optic_nodes, only: [:index, :show, :update, :create]
      resources :results, only: [:index, :show, :update, :create]
      resources :profiles, only: [:index, :show, :update, :create]
      resources :sections, only: [:index, :show, :update, :create]
      resources :threat_assessment_runs, only: [:index, :show, :update, :create]
      resources :threat_assessments, only: [:index, :show, :update, :create]
      resources :timelines, only: [:index, :show, :update, :create]
      resources :contexts, only: [:index, :show]
      resources :experiments, only: [:index, :show, :update, :create]
      resources :scenarios, only: [:index, :show, :update, :create]
      resources :monitoring, only: [:index]
      resources :chart_exporter, only: [:index]
      resources :experiment_exporter, only: [:show, :index]
      resources :threat_levels, only: [:index]
      resources :anomaly_data, only: [:index]
    end
  end

  get 'help' => 'help#index'
  get 'help/api' => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  skip_authorization_check

  def index

  end

  def api
    @category = params[:category]
    @category = "README" if @category.blank?

    if File.exists?(Rails.root.join('doc', 'api', @category + '.md'))
      render 'api'
    else
      not_found!
    end
  end
end

app/views/help/api.html.haml
.row
  .col-md-2
    %h2
      = link_to help_path, class: 'btn btn-default btn-xs' do
        =fa_icon 'angle-left'
        = t 'help.back'
      %span.pull-right API
    %hr

    #ul.nav.nav-pills.nav-stacked
      - %w(anomaly_data budokop_sensors contexts experiments scenarios device_aggregations devices edge_nodes levees measurement_nodes measurements neosentio_sensors parameters pumps fiber_optic_nodes profiles timelines threat_assessments threat_assessment_runs results sections monitoring threat_levels).sort.each do |file|
        = nav_tab :category, file do
          = link_to file.titleize, help_api_file_path(file)
  .col-md-10
    = preserve do
      = markdown File.read(Rails.root.join("doc", "api", "#{@category}.md"))

app/views/help/index.html.haml
%h1 Help

.row
  .col-md-3
    %ul.nav
      %li= link_to API, help_api_path
  .col-md-9
    Help content